---
- hosts: pc
  vars_files:
    - 'vars/{{ ansible_distribution }}.yml'
    - vars/packages.yml
  tasks:
    - name: Prepare AppImage space
      file:
        state: directory
        path: '{{ ansible_env.HOME }}/.local/opt'
    - name: Download and link AppImages (Linux only)
      block:
        - get_url:
            url: '{{ item.url }}'
            dest: '{{ ansible_env.HOME }}/.local/opt/{{ item.name }}'
          with_items: '{{ packages_master|by_module("appimage") }}'
        - file:
            src: '{{ ansible_env.HOME }}/.local/opt/{{ item.name }}'
            dest: '{{ ansible_env.HOME }}/.local/bin/{{ item.name }}'
            state: link
            mode: 'u+x'
          with_items: '{{ packages_master|by_module("appimage") }}'
      when: ansible_distribution == 'Archlinux'
