# --------------------------------------
# Settings for desktop environment(arch only)
# --------------------------------------
---
- hosts: pc
  vars_files:
    - 'vars/{{ ansible_distribution }}.yml'
  vars:
    packages:
      # Video for intel
      - xf86-video-intel
      - mesa
      # Descktop
      - xorg-server
      - xorg-xinit
      - xorg-xinput
      - xorg-xrandr
      - qtile
      # IME
      - fcitx
      - fcitx-mozc
      - fcitx-configtool
  tasks:
    - name: Install packages
      become: yes
      pacman:
        name: '{{ packages }}'
      when: ansible_distribution == 'Archlinux'
    - name: Use ssh-agent
      block:
        - copy:
            src: ssh-agent.service
            dest: '{{ ansible_env.HOME }}/.config/systemd/user/ssh-agent.service'
        - systemd:
            name: ssh-agent
            scope: user
            state: started
            enabled: yes
      tags: config
    - name: Set xinitrc
      template:
        src: xinitrc.j2
        dest: '{{ ansible_env.HOME }}/.xinitrc'
      tags:
        - config
    - name: Set Qtile configuration
      block:
        - file:
            state: directory
            path: '{{ ansible_env.HOME }}/.config/qtile'
        - template:
            src: qtile_config.py.j2
            dest: '{{ ansible_env.HOME }}/.config/qtile/config.py'
      tags:
        - config
