---
- hosts: pc
  vars_files:
    - 'vars/{{ ansible_distribution }}.yml'
  tasks:
    - include_tasks: tasks/setup_packages.yml
      with_items:
        - pacman: fontconfig
    - name: Prepare directory
      file:
        state: 'directory'
        path: '{{ dirs.fonts }}'
    - name: Link user fonts
      file:
        state: 'link'
        src: '{{ item }}'
        dest: '{{ dirs.fonts }}/{{ item|basename }}'
      with_items: '{{ lookup("dirglob", ansible_env.PWD + "/../files/fonts/*", wantlist=True) }}'
      notify:
        - Reload fonts
      tags:
        - fonts
  handlers:
    - name: Reload fonts
      shell: fc-cache
