# --------------------------------------
# Settings for packages by only tools
# --------------------------------------
---
- hosts: pc
  vars_files:
    - vars/packages.yml
  tasks:
    - name: Install packages by pacman(arch only)
      become: yes
      pacman:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      with_items: '{{ packages_master|by_module("pacman") }}'
