# --------------------------------------
# Settings for packages by only tools
# --------------------------------------
---
- hosts: pc
  vars_files:
    - 'vars/{{ ansible_distribution }}.yml'
    - vars/packages.yml
  tasks:
    - name: Install packages by pacman(arch only)
      become: yes
      pacman:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      with_items: '{{ packages_master|by_module("pacman") }}'
      when: ansible_distribution == 'Archlinux'
    - block:
        - name: Install packages by homebrew(mac only)
          homebrew:
            name: '{{ item.name }}'
            state: '{{ item.state }}'
          with_items: '{{ packages_master|by_module("homebrew") }}'
        - name: Install packages by homebrew-cask(mac only)
          homebrew_cask:
            name: '{{ item.name }}'
            state: '{{ item.state }}'
          with_items: '{{ packages_master|by_module("homebrew_cask") }}'
      when: ansible_distribution == 'MacOSX'
    - name: Install packages by pip(path specified only)
      pip:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
        executable: '{{ commands.pip }}'
        extra_args: --user
      with_items: '{{ packages_master|by_module("pip") }}'
      when: '"pip" in commands'
