---
packages_master:
  # alacritty
  - modules:
      pacman: alacritty
      homebrew: alacritty
  # tig
  - modules:
      pacman: tig
      homebrew: tig
  # NeoVim: As bare Vim (vim is used many plugin as small IDE)
  - modules:
      pacman: neovim
      homebrew: neovim
  # GitKraken
  - modules:
      homebrew_cask: gitkraken
  # Django(for django-admin)
  - modules:
      pip: django
  # nvm (Node executable manager)
  - modules:
      homebrew: nvm
  # httpie
  - modules:
      pip: httpie
  # cookiecutter
  - modules:
      pip: cookiecutter
  # poetry
  - modules:
      pip: poetry