---
# tasks file for attakei.xonsh
- name: Install xonsh
  pip:
    name: xonsh
    state: present
    extra_args: '{{ xonsh__pip_args }}'
- name: Install xontribs
  # TODO: Use comand module currently, fix for idempotence. 
  command: 'xonsh -c "xontrib install {{ item }}"'
  with_items: '{{ xonsh__xontribs }}'
