---
- name: Install zsh
  become: yes
  pacman:
    name: zsh
    state: present
  when: ansible_distribution == 'Archlinux'
  tags:
    - zsh
- name: Enable as login-shell
  become: yes
  user:
    name: '{{ ansible_env.USER }}'
    shell: '{{ zsh__bin_path }}'
  when: zsh__as_login_shell
- name: Setup Zinit
  git:
    repo: https://github.com/zdharma-continuum/zinit.git
    dest: '{{ zsh__zinit_home }}'
