# --------------------------------------
# Build docker container for VSCode workspaces
# --------------------------------------
---
- hosts: pc
  vars:
    images:
      - python3
    image_source_dir: "{{ ansible_env.HOME }}/ws/files/containers"
  tasks:
    - name: Build local workspace
      docker_image:
        build:
          path: "{{ image_source_dir }}/{{ item }}"
        name: "attakei/workspace"
        tag: "{{ item|basename }}"
        push: yes
        source: build
      with_items: "{{ images }}"
