---
- hosts: pc
  vars_files:
    - 'vars/{{ ansible_distribution }}.yml'
  tasks:
    - include_tasks: tasks/setup_packages.yml
      with_items:
        - pacman: fontconfig
    - name: Prepare directory
      file:
        state: 'directory'
        path: '{{ dirs.fonts }}'
    - name: Fetch user fonts
      unarchive:
        src: '{{ item }}'
        dest: '{{ ansible_env.HOME }}/.local/share/fonts/'
        remote_src: yes
      with_items:
        - https://github.com/rayshan/mplus-fonts/archive/master.zip
        - https://github.com/edihbrandon/RictyDiminished/archive/master.zip
      notify:
        - Reload fonts
      tags:
        - fonts
  handlers:
    - name: Reload fonts
      shell: fc-cache
